class_name EOSCredentialsTemplate

const PRODUCT_NAME = "HexArena"
const PRODUCT_VERSION = "1.0"

const PRODUCT_ID = "PUT_PRODUCT_ID_HERE"
const SANDBOX_ID = "PUT_SANDBOX_ID_HERE"
const DEPLOYMENT_ID = "PUT_DEPLOYMENT_ID_HERE"

const CLIENT_ID = "PUT_CLIENT_ID_HERE"
const CLIENT_SECRET = "PUT_CLIENT_SECRET_HERE"

const ENCRYPTION_KEY = "PUT_64_HEX_CHARACTER_ENCRYPTION_KEY_HERE"
